#!/usr/bin/env python3
"""
Pull the latin subsets of the site's typefaces from Google Fonts and write
them into assets/fonts/, plus the @font-face rules in assets/fonts.css.

The site self-hosts its fonts so the page makes no third-party request and
renders identically whether or not fonts.googleapis.com is reachable — which
matters more on a Zimbabwean connection than Google's cache ever did.

Run from the repository root:   python3 tools/fetch-fonts.py

All three families are variable fonts, so one file per family covers every
weight in the declared range.
"""
import re, os, urllib.request

UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

# (family, Google query, local basename, weight range used on the site, stretch)
FAMILIES = [
    ('Archivo',       'Archivo:wght@500;600;700', 'archivo',  '500 700', '100%'),
    ('Inter',         'Inter:wght@400;500',       'inter',    '400 500', None),
    ('IBM Plex Mono', 'IBM+Plex+Mono:wght@400',   'plexmono', '400',     None),
]

OUT_DIR = 'assets/fonts'
OUT_CSS = 'assets/fonts.css'


def fetch(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    return urllib.request.urlopen(req, timeout=60).read()


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    blocks, total = [], 0

    for family, query, base, weights, stretch in FAMILIES:
        css = fetch('https://fonts.googleapis.com/css2?family=%s&display=swap' % query).decode()

        # Keep the latin subset only. Every weight of a variable family points
        # at the same file, so the first latin block is all we need.
        m = re.search(r'/\*\s*latin\s*\*/\s*@font-face\s*\{(.*?)\}', css, re.S)
        if not m:
            raise SystemExit('no latin subset found for ' + family)
        block = m.group(1)

        url = re.search(r'src:\s*url\((https://[^)]+\.woff2)\)', block).group(1)
        rng = re.search(r'unicode-range:\s*([^;]+);', block).group(1).strip()

        name = base + '.woff2'
        data = fetch(url)
        open(os.path.join(OUT_DIR, name), 'wb').write(data)
        total += len(data)
        print('%-15s %6.1f KB  %s' % (family, len(data) / 1024, name))

        rules = ['  font-family: "%s";' % family,
                 '  font-style: normal;',
                 '  font-weight: %s;' % weights]
        if stretch:
            rules.append('  font-stretch: %s;' % stretch)
        rules += ['  font-display: swap;',
                  '  src: url("fonts/%s") format("woff2");' % name,
                  '  unicode-range: %s;' % rng]
        blocks.append('@font-face {\n' + '\n'.join(rules) + '\n}')

    header = ('/* Generated by tools/fetch-fonts.py — do not hand-edit.\n'
              '   Self-hosted latin subsets. Variable fonts, so one file per family\n'
              '   covers the whole declared weight range. */\n')
    open(OUT_CSS, 'w').write(header + '\n' + '\n\n'.join(blocks) + '\n')
    print('\n%.1f KB total  ->  %s' % (total / 1024, OUT_CSS))


if __name__ == '__main__':
    main()
